name: klondike
description: "Klondike Solitaire"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  desktop_window: ^0.4.0
  flame: ^1.11.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  line_awesome_flutter: ^2.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets\images\klondike-sprites.png